version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install

artifacts:
  files:
    - target/UserInfo-1.0-SNAPSHOT.jar
    - appspec.yml
    - Scripts/AppStart.sh
  discard-paths: yes